CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(20) DEFAULT NULL,
	last_name VARCHAR(20) DEFAULT NULL,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
	id SERIAL PRIMARY KEY,
	description TEXT DEFAULT NULL,
	is_done BOOLEAN DEFAULT 'f',
	title VARCHAR(255) DEFAULT NULL,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);